# Site settings
title: Parkdale People's Assembly
email:
description:
url: 
github: https://github.com/jtloong/parkdale-tracker/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  - html-proofer

sass:
  sass_dir: css/partials
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - misc
  - script
  - Rakefile

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
